### PR TITLE
feat(STONEINTG-698): remove ephemeral environment references

### PR DESCRIPTION
**Pull request by dirgim**
* Remove all references to ephemeral environments from the integration service architecture document

### CODE REVIEW

**Review by arewm — DISMISSED** [review]
I believe that there are some references to environments in the diagrams/images. Can you also remove those?

Note: this will likely conflict with #180 if that is merged first.

**Comment by dirgim** [comment]
> I believe that there are some references to environments in the diagrams/images. Can you also remove those?
> 
> Note: this will likely conflict with #180 if that is merged first.

I'm planning to have a follow-up PR to update the integration service diagram to a new format since Lucid Charts (where the original diagram was made) are not available anymore.

**Review by jsztuka — APPROVED** [review]
Looks good, needs rebase.

**Review by ralphbean — APPROVED** [review]

**Comment by ralphbean** [comment]
LGTM. @dirgim do you have rights to merge?

**Comment by dirgim** [comment]
@arewm are you ok with the current changes included here? The environment references have already been removed from the existing diagrams in previous PRs.

**Review by kasemAlem — APPROVED** [review]

**Review by hongweiliu17 — APPROVED** [review]

**Review by arewm — APPROVED** [review]

**Pull request merged**
