### PR TITLE
Update architecture docs to reflect current state of HAS

### PR DESCRIPTION
**Pull request by johnmcollier**
Updates the Konflux architecture docs to accurately represent the current state of HAS within Konflux: a deployment that runs Kubernetes webhooks for Applications and Component resources

### CODE REVIEW

**Review by ifireball — APPROVED** [review]
LGTM

**Review by elsony — CHANGES_REQUESTED** [review]
There are other places in the doc that references HAS info, e.g. https://github.com/konflux-ci/architecture/blob/main/architecture/index.md. We should do a search for the entire doc to make sure we remove all references and avoid link breakage.

**Comment by johnmcollier** [comment]
@elsony Good suggestion. I checked through the remaining docs for both `HAS`, `HAS/` and `application-service` and didn't find anything that was broken by the doc removal.

I do see some outdated references to HAS, so I updated those with one exception: The architecture diagram and explanation of CRs in index.md, which I left alone, as it's outside of the scope of these changes (and outside of our team's scope now).

**Review by elsony — APPROVED** [review]

**Pull request merged**
