### PR TITLE
Replace most mentions of AppStudio with Konflux

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by arewm** [comment]
Do you want to change the relevant file names or references within the images as well?

**Comment by ralphbean** [comment]
@arewm hm, yes. Let's do that here.

**Comment by ralphbean** [comment]
@arewm I updated to include diagram changes now and a few filename changes too.

**Review by arewm — APPROVED** [review]
I trust what you have done and won't double-check it. We can continue to replace references as we discover them.

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
